services:
  zver:
    build:
      context: .
      dockerfile: Dockerfile.build
    image: zver:build
    volumes:
      - ./bin:/src/bin
      - ./.cache/Nuitka:/root/.cache/Nuitka
    container_name: zver-build
    network_mode: host
